---
apiVersion: v1
data:
  pranit.conf: |
    This is my configuration file...pranit here !!
kind: ConfigMap
metadata:
  name: config-pranit-az

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-pd-az
type: Opaque
data:
  username: cHJhbml0
  password: cHJhbml0MTIz

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment-pd-az
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeserver
          image: thetips4you/nodeapp:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: testconfigmap
              mountPath: /tmp/config
            - name: testsecret
              mountPath: /tmp/mysecrets
      volumes:
        - name: testconfigmap
          configMap:
            name: config-pranit-az
            items:
              - key: pranit.conf
                path: pranit.conf
        - name: testsecret
          secret:
            secretName: secret-pd-az

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc-pd-az
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31132
